spring:
 flyway:
  locations: 'classpath:db/migration_local/'
 jpa:
  show-sql: true
 datasource:
  url: 'jdbc:h2:mem:test'
 h2.console:
  enabled: true
  path: '/h2'
androidapp:
 web-server-url: 'http://localhost:8080'
 innactive-token-validity-in-days: 1
 registration:
  allowedAttempsAmount: 20
  suspentionTimeInHours: 1